buildscript {
    repositories {
        google()
        mavenCentral()
        jcenter()
    }
    dependencies {
        // ✅ AGP 3.6.4 = bản cao nhất VẪN HỖ TRỢ support library cũ, desugar được bytecode 0.17.1
        classpath 'com.android.tools.build:gradle:3.6.4'
        classpath 'org.androidannotations:androidannotations:4.6.0'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        jcenter()
        maven { url "https://jitpack.io" }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
