apply plugin: 'com.android.application'

android {
    compileSdkVersion 26
    buildToolsVersion "26.0.2"
    defaultConfig {
        applicationId "com.example.thinkmobiles.bitcoinwalletsample"
        minSdkVersion 16
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
        vectorDrawables.useSupportLibrary = true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:26.0.2'
    implementation 'com.android.support:design:26.0.2'
    implementation 'com.android.support:recyclerview-v7:26.0.2'
    implementation 'com.android.support:support-v4:26.0.2'
    implementation 'com.android.support:transition:26.0.2'
    implementation 'com.android.support:multidex:1.0.2'

    implementation 'org.androidannotations:androidannotations-api:4.6.0'
    annotationProcessor 'org.androidannotations:androidannotations:4.6.0'

    implementation 'com.google.zxing:core:3.2.0'
    implementation 'com.journeyapps:zxing-android-embedded:3.5.0'
    implementation 'com.github.kenglxn.QRGen:android:2.2.0'
   // implementation 'org.bitcoinj:bitcoinj-core:0.14.4'
    implementation 'org.bitcoinj:bitcoinj-core:0.16.5'
    implementation 'com.squareup.okhttp:okhttp:2.7.2'
    // ✅ ĐÃ SỬA LỖI QUAN TRỌNG: thiếu tên thư viện okio
    implementation 'com.squareup.okio:okio:1.6.0'
    implementation 'org.slf4j:slf4j-api:1.7.20'
    implementation 'org.slf4j:slf4j-simple:1.7.12'
}
